apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mkto2c509-go
  janus-idp.io/tekton: mkto2c509-go
  backstage.io/kubernetes-id: mkto2c509-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mkto2c509-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
